{{ $nodepool := .Values.cluster }}
{{- if $nodepool }}
apiVersion: rke-machine-config.cattle.io/v1
kind: DigitaloceanConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-local
image: ubuntu-20-04-x64
region: sfo3
size: s-2vcpu-4gb
sshPort: "22"
sshUser: "root"
{{- end}}
