annotations:
  catalog.cattle.io/namespace: fleet-default
  catalog.cattle.io/type: cluster-template
apiVersion: v1
description: Cluster template with registry option enabled
name: qa-registry-template
version: 0.0.1
