annotations:
  catalog.cattle.io/namespace: fleet-default
  catalog.cattle.io/type: cluster-template
apiVersion: v1
description: Example cluster template for rke2 - updated questions
name: default-template
version: 0.0.2
